version: '2'

services:
  redis:
    image: 'redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/var/lib/redis/data'

volumes:
  redis_data:
    driver: local
